apiVersion: v2
name: transmission-cleaner
description: Transmission cleaner operations for torrent automation
home: https://gitlab-internal.spirit-dev.net/infrastructure/helm/xarr/transmission-cleaner
sources:
  - https://gitlab-internal.spirit-dev.net/infrastructure/helm/xarr/transmission-cleaner

type: application

# Note: This is a custom internal chart without external dependencies
version: "1.0.0"

# Note: This is a custom internal application
appVersion: "1.0.0"

keywords:
  - torrent
  - transmission
  - cleaner
